#!/usr/bin/env bash
#
# One-shot setup for a fresh Ubuntu/Debian box. Idempotent: safe to re-run.
#
#   bash deploy/bootstrap.sh                        # HTTP on the bare IP
#   bash deploy/bootstrap.sh crm.example.com        # HTTPS, needs DNS first
#
# Installs Docker, writes .env with generated secrets, opens the firewall,
# builds and starts the stack, and provisions a client to connect machines to.
#
# WHAT IT DOES NOT OPEN, deliberately:
#   redis     publishes no port at all. The api and worker reach it over the
#             compose network. An internet-facing Redis with no password is one
#             of the most reliably exploited misconfigurations there is -- boxes
#             get found and mined within minutes of coming up. Nothing needs it
#             exposed for this to work.
#   postgres  127.0.0.1:5432 only. Same reasoning; use `docker compose exec db
#             psql` or an SSH tunnel to reach it.
#   minio     127.0.0.1:9000/9001 only. Sheets are served through the API.
# Only 22, 80 and 443 face the internet.
set -euo pipefail

SITE="${1:-}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m    %s\033[0m\n' "$*"; }

[ "$(id -u)" -eq 0 ] || { echo "run as root"; exit 1; }

# ---------------------------------------------------------------- docker -----
if ! command -v docker >/dev/null 2>&1; then
  say "installing Docker"
  # Docker's own repo, not apt's docker.io: the distro package lags and ships
  # the standalone docker-compose v1, while this project's compose file needs
  # v2 (`docker compose`, no hyphen).
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg >/dev/null
  install -m 0755 -d /etc/apt/keyrings
  . /etc/os-release
  curl -fsSL "https://download.docker.com/linux/${ID}/gpg" \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin >/dev/null
  systemctl enable --now docker
else
  say "Docker already installed: $(docker --version)"
fi

# -------------------------------------------------------------- firewall -----
say "firewall"
if command -v ufw >/dev/null 2>&1; then
  ufw allow 22/tcp   >/dev/null 2>&1 || true   # before enabling, or you lock yourself out
  ufw allow 80/tcp   >/dev/null 2>&1 || true
  ufw allow 443/tcp  >/dev/null 2>&1 || true
  yes | ufw enable   >/dev/null 2>&1 || true
  ufw status | sed 's/^/    /'
else
  warn "ufw not present; assuming the provider's firewall allows 22/80/443"
fi

# ------------------------------------------------------------------ .env -----
if [ ! -f .env ]; then
  say "writing .env"
  gen() { openssl rand -base64 33 | tr -d '/+=' | cut -c1-32; }

  : "${APIMART_API_KEY:?set APIMART_API_KEY in the environment before running, e.g. APIMART_API_KEY=sk-... bash deploy/bootstrap.sh}"
  UI_USER="${UI_USER:-operator}"
  UI_PASSWORD="${UI_PASSWORD:-$(gen)}"
  # Caddy hashes it; the plaintext never reaches disk except in this message.
  UI_HASH="$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "$UI_PASSWORD")"

  cat > .env <<EOF
# Generated by deploy/bootstrap.sh. Secrets here are random per machine.
APIMART_API_KEY=${APIMART_API_KEY}
APIMART_BASE_URL=https://api.apimart.ai/v1

POSTGRES_USER=snap
POSTGRES_PASSWORD=$(gen)
POSTGRES_DB=snap
POSTGRES_PORT=5432

MINIO_ROOT_USER=snapminio
MINIO_ROOT_PASSWORD=$(gen)
MINIO_BUCKET=sheets
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001

# ':80' serves plain HTTP on whatever address you hit, which is what you want
# before DNS exists. A hostname here makes Caddy issue a real certificate --
# and it will FAIL if that name does not already resolve to this box.
SITE_ADDRESS=${SITE:-:80}

OPERATOR_API_KEY=op_$(gen)
UI_USER=${UI_USER}
UI_PASSWORD_HASH=${UI_HASH}

EXTRACT_CONCURRENCY=16

# 0 = delete each sheet image the moment its pipeline commits. At ~1.2MB a sheet
# and 20k/day that is the difference between flat storage and ~24GB/day.
SHEET_RETENTION_DAYS=0
SHEET_FAILED_KEEP_MAX=20
RETENTION_SWEEP_MINUTES=60
EOF
  chmod 600 .env
  echo "$UI_PASSWORD" > .ui-password
  chmod 600 .ui-password
  warn "operator login: ${UI_USER} / ${UI_PASSWORD}   (also in .ui-password)"
else
  say ".env already exists, leaving it alone"
fi

# ------------------------------------------------------------------- up ------
say "building and starting"
docker compose up -d --build

say "waiting for the API"
for i in $(seq 1 60); do
  if docker compose exec -T api node -e \
      "fetch('http://127.0.0.1:3000/api/personalities',{headers:{Authorization:'Bearer x'}}).then(r=>process.exit(r.status===401?0:1)).catch(()=>process.exit(1))" \
      >/dev/null 2>&1; then
    echo "    up after ${i}s"; break
  fi
  sleep 1
  [ "$i" = 60 ] && { warn "API did not come up; docker compose logs api"; exit 1; }
done

say "done"
IP="$(curl -fsS4 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')"
ADDR="${SITE:-$IP}"
cat <<EOF

  CRM        http://${ADDR}/            (operator login above)
  agents     http://${ADDR}/v1/...      no login, per-machine API key

  Next:

  1. Provision a client and its accounts:
       docker compose exec api node dist/cli/provision.js \\
         --client "my agency" --personality kris \\
         --accounts kris_snap_01,kris_snap_02 --cap 240

  2. Open enrolment for 10 minutes (the operator key is in .env):
       curl -X POST http://127.0.0.1:3000/api/enrolment/open \\
         -H "Authorization: Bearer \$(grep ^OPERATOR_API_KEY .env | cut -d= -f2)" \\
         -H 'Content-Type: application/json' -d '{"minutes":10}'

  3. On each emulator machine, run start.bat and type into Connect:
       ${ADDR}

EOF
